name: simple workflow 
on: 
  push: 
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest   # define the runner 
    steps:
      - name: print a welcome message
        run: echo "welcome to our first github action workflow."
        
      - name: Checkout repository 
        uses: actions/checkout@v6.0.0
        
      - name: list repository files 
        run: ls -la 
  
